use alumni;
SELECT * FROM alumni.students;

INSERT INTO alumni.students (fullName,nickName,email,gender,address,batchName) 
VALUES ("Andrew","Endru", "sbstn.andrew56@gmail.com","Male", "Jl. Tanjung Duren Raya, Apt Mediterania Residences 1 Tower Azalea 27 B/L","#1 Avalon"),
("Arian Markus P Hutagalung","Arian","arianmarkus77@yahoo.com","Male","Jl. Tumaritis No 14 Cilandak Barat RT 005 RW 003","#1 Avalon"),
("Hafidz Ilham Aji Permana","Hafidz","hey.hafidz@gmail.com","Male","Jl. Glatik No. 44 RT/RW 01/03, Kebon, Kelurahan Ploso","#1 Avalon"),
("Moh Amirul Fatta","Amir","it.amirulfatta@gmail.com","Male","Komp. Nusantara Golden Blok No. 10","#1 Avalon"),
("Thoriq Nur Faiza","Thoriq","thoriqnfaizal@gmail.com","Male","Kalibaru Permai, Blok C5 No 2","#1 Avalon"),
("Yonatan Putra Widjojo","Yonatan","yonatanwidjojo@yahoo.com","Male","Casablanca East Residence BA2- 7, Pahlawan Revolusi 2","#1 Avalon"),
("Aditia Darmadi Jiwandono","Dono","aditiadarmadij@gmail.com","Male","Jalan Raya Purwasari Nomor 5 RT.01/RW.03, Kecamatan Purwasari","#2 Bahamut"),
("Angeline Go","Angel","angeline_go87@hotmail.com","Female","Jl Pluit Samudra 5 no.15, Jakarta Utara 14450","#2 Bahamut"),
("Ferryal Muhamad Fajar Bahari","Feri","ferryal21@gmail.com","Male","Jalan Bangau 3 no.14 Rumpun Diponegoro","#2 Bahamut"),
("Fikri Muhammad","Fikri","fikrimsanad93@gmail.com","Male","Jl. Panjang Kp Baru No. 23","#2 Bahamut"),
("Miftahul Agtamas Fidyawan","Mifta","agtamasmiftahul37@gmail.com","Male","Jalan Sri Waluyo 4 RT. 15/RW. 06 Desa Tiron,  Kecamatan Madiun,  Kabupaten Madiun, Jawa Timur,  63151","#2 Bahamut"),
("Muhammad Fahri Abdul Hakim","	Fahri","fahriabdhakim@yahoo.com","Male","Jl. Jamblang No.5 Pejaten Raya Pasar Minggu Jakarta Selatan 12540","#2 Bahamut"),
("Muhammad Haekal","Haekal","93haekal@gmail.com","Male","Jl.Melati No.157 Komplek Kodam, Kebon Jeruk, Jakarta Barat","#2 Bahamut"),
("Muhammad Haidar Dzaky","Dzaky","haidardz@gmail.com","Male","Jl. Sarimas Raya No.25, Arcamanik, Bandung","#2 Bahamut"),
("Oliver Audhie","	Oliver","slumantri@gmail.com","Male","Jl. Kedondong No. 11","#2 Bahamut"),
("Abdurrahman Fadhil"," Fadhil","rhmnfadhil@gmail.com","Male","GDC, Sektor Alamanda, Blok A3/3, Depok, 16413","#3 Charizard"),
("Ali Kurniawan","Ali","Oliver","alikoerniawan02@gmail.com","Male","Jl. Bintan block f1 no. 331 RT.09/07 perum Pondok Aren ciluar Bogor jawa barat","#3 Charizard"),
("Fuad Baskara Priyambada"," Fuad","Oliver","fuadbaskara@gmail.com","Male","Perum. Rancho indah jl.tanjung 16 blok.i no.16 rt/rw 07/02. Tanjung barat, jagakarsa, jakarta selatan.","#3 Charizard"),
("Kien Doan"," Kien","	Oliver","kien.doan@gmail.com","Male","17286 Via AlamitosSan Lorenzo, CA 94580","#3 Charizard"),
("Muhammad Najib Kusumonegoro"," Najib","virtualnajib@gmail.com","Male","Jl. Haji Hasan no. 33A, RT3/RW2, Baru, Pasar Rebo, Jakarta Timur","#3 Charizard"),
("Rizal Zulkarnain","Rizal","naenroo@gmail.com","Male","Jln.Imam Rasyidi No.66b Rt.03 Rw.02 Siraman Dukun Gresik Jawa Timur","#3 Charizard"),
("Herdanu Yudistira Putra","Danu","heh.danu@gmail.com","Male","Jl. Flamboyan Raya - Balikpapan Baru, Montreal GC 06","#3 Charizard"),
("Miftah Faris","Miftah","	Oliver","miftahmfaris@yahoo.co.id","Male","Jl. Pisangan Baru Tengah No. 26B RT001/RW012 Kel. Pisangan Baru Kec. Matraman Jakarta Timur","#3 Charizard"),
("Stefanus Dody Kristianto Wicaksono","Dody","stefanusdody@yahoo.com","Male","Komplek Pura Melati Indah Blok E no 6 Tahap 2, Pondok Gede - Bekasi","#3 Charizard"),
("Yanuar Yudhistira","Yanuar","yanuar.yudhistira@gmail.com","Male","Jl. Jambore Raya No. D3 Cibubur Ciracas","#3 Charizard"),
("Dei Gratia Radrigov Rahawarin","Dei","rdeigratia95@gmail.com","Male","Larangan Mega Asri B-146 sidoarjo","#3 Charizard"),
("Dedek Julianto","Dedek","dedekproject@gmail.com","Male","Jl. Pupan RT 10 RW 08 No 68 B, Pondok Pinang, Kebayoran Lama, Jakarta Selatan","#3 Charizard"),
("Arthur Farellio","Arthur","arthurfarellio32@gmail.com","Male","Batam","#4 Drogon"),
("Indra Putra","Indra","indrakoslab@gmail.com","Male","Pekanbaru","#4 Drogon"),
("Jamaluddin bin Marzuki","Jamal","jamaluddinbinmarzuki@gmail.com","Male","Batam","#4 Drogon"),
("Welly Andriani","Welly","wellyandriani97@gmail.com","Female","Batam","#4 Drogon"),
("Fadillah Bilqis","Dillah","fadillah.bilqis@gmail.com","Female","Batam","#4 Drogon"),
("Wondo Indra","Wondo","wondoindra28@gmail.com","Male","Batam","#4 Drogon"),
("Cristina Shuw","Cristin","cristinashuw@gmail.com","Female","Batam","#4 Drogon");